### ISSUE TITLE
More than one unit

### ISSUE THREAD

**Issue by nilskt** [aglehmann/home_assistant_ecovent#1]
Is it possible to add more than one unit? 
When I try to add more than one in configuration.yaml, I get a duplicate-error.

**Comment by aglehmann** [comment]
At the moment no, this is still work in progress. Handling multiple devices shouldn’t be too hard to implement, I’ll have a look at it next week. What kind of units are you trying to include?

**Comment by nilskt** [comment]
That sounds great!
I have 3 Twinfresh Expert RW1-50 units. 

Thank you for making this great plugin!

**Comment by aglehmann** [comment]
I am glad this is useful for others and a little surprised that you found it before I advertised it anywhere.

I’ll get back to you on the multiple unit support.

**Comment by aglehmann** [comment]
I have updated the component so it should support multi units now. Note that the configuration has changed, please see the readme for details. 

The input validation was sort of lost in the process, I want to get that back so things might change in the future.

Appreciate feedback if this works or not.

**Comment by nilskt** [comment]
I just upgraded and reconfigured the component on my Home Assistant and it works great with my three fans! Well done and thank you very much!

**Comment by aglehmann** [comment]
Awesome! Thank you for your feedback.
