### ISSUE TITLE
How to turn on the fan using the latest version of Home Assistant Core

### ISSUE THREAD

**Issue by gullesen** [aglehmann/home_assistant_ecovent#13]
With the latest release of Home Assistant Core (2021.3.2), fans got an overhaul. The service fan.turn_on doesn't work anymore. I have the Flexit Roomie Dual Wifi, and this component has worked excellent with previous core releases. I am able to use service calls to change the fan speed (fan.set_percentage) and turn the fan off (fan.turn_off, or fan.set_percentage = 0), but I cant't turn the fan back on using any service call. 

Anyone have a solution?

**Comment by Damjank1975** [comment]
I have the same issue with the latest version of Home Assistant Core. Anyone have a solution?

**Comment by aglehmann** [comment]
Hi, thanks for notifying me about this issue.
I just pushed an update to rectify this particular problem. If you are using HACS you can simply update the custom component from HACS , if not then you need to pull the latest version from this repo.

Appreciate feedback if this works or not.

**Comment by gullesen** [comment]
Hi! The update fixed the issue. Thank you!

**Comment by Damjank1975** [comment]
Hi. Perfect! Well done job.

Thank you.
