### ISSUE TITLE
Cannot add entity because of speed error in logs of HA

### ISSUE THREAD

**Issue by larsmag12** [aglehmann/home_assistant_ecovent#14]
I have had problems with setting this up since HA changed the way they are dealing with speed. I have tried to update the plugin and even deleting it starting from scratch. The problem is that i can't get it to be shown as an entity in HA anymore. Please see the enclosed errors from the logs in HA.
![Ecovent 2](https://user-images.githubusercontent.com/28041942/115395772-8cb1a580-a1e4-11eb-9c57-064acac9d6fd.png)
![ecovent](https://user-images.githubusercontent.com/28041942/115395786-90ddc300-a1e4-11eb-9160-a215cf59b7ee.png)

**Comment by aglehmann** [comment]
Hi, thank you for reporting this issue. Which version of HA are you running?

**Comment by larsmag12** [comment]
I'm running the latest one 2021.4.6. Not beta but the stable version. Thanks for the fast reply :)

**Comment by larsmag12** [comment]
If you need more info and logs please let me know.

**Comment by aglehmann** [comment]
I tried reproducing the issue but I was unable to provoke the same behavior. How did you install the component? HACS or manually by pulling the code?

**Comment by larsmag12** [comment]
I did HACS first, then tried it manually. I think it must be something with my setup since you haven't heard anything from the other users. What's your tip on trying to resolve this?

**Comment by larsmag12** [comment]
Do you know if the ip range has to be 192.168.x.x or can it also be 10.0.0.x? I just added an entity with a false ip and that one show straight away while my product with 10.0.0.x is not showing....

**Comment by aglehmann** [comment]
That is really strange, the ip addresse range should not maked any difference. But it might be that when you use the correct ip address more of the code in the component is exeuted which in turn gives you the error message. I have to do some debugging to find where the error originates from.

Did this work before you upgraded to the newest version of HA or is this the first time you are trying the component?

**Comment by larsmag12** [comment]
Ok, that makes sense. This worked perfectly before HA changed their way of handling speed with fans in march, then it broke. And I waited for your update and tried installing it but no success...

**Comment by larsmag12** [comment]
Hi! I found the error but I don't have a clue why it worked. It seems like some text was in customization.yaml file, after I deleted the text it worked. The text was something like the entity name e.g basement fan. Don't know if this makes sense to you? Everything seems to be working like it should now so you can close this one.

**Comment by aglehmann** [comment]
I'm glad to hear that. I don't understand why the customization.yaml would make any difference to how this component work, but I haven't used that my self so I don't know exactly what it does.
