### ISSUE TITLE
Breaking change - "version" missing in manifest.json

### ISSUE THREAD

**Issue by mycortex** [aglehmann/home_assistant_ecovent#15]
I just modified the file to get it working. Would be great if you could fix this in your repo

This code in manifest.json works:
{
  "domain": "ecovent",
  "name": "EcoVent",
  "documentation": "https://github.com/aglehmann/pyEcovent",
  "dependencies": [],
  "codeowners": ["@aglehmann"],
  "requirements": ["pyEcovent>=0.8.3"],
  "version": "1.0.0"
}

**Comment by aglehmann** [comment]
Version key is now added. It works for me, please let me know if you still have issues.
