### ISSUE TITLE
integration is not installed

### ISSUE THREAD

**Issue by aleksman-piter** [aglehmann/home_assistant_ecovent#17]
Good afternoon, added integration via hacs, restarted the server, added entries to the configuration.yaml, an error appeared
Component error: ecovent - Integration 'ecovent' not found.
only i'm so lucky?
home assistant core-2021.6.6 with supervisor-2021.06.3

**Comment by robinostlund** [comment]
Check #15 as in newer version of homeassistant version in manifest is required. And this repo havent been updated yet, so just add version to manifest as in #15

**Comment by aleksman-piter** [comment]
Tried it, did not help, the error is the same. the code was taken from question 15.

**Comment by aglehmann** [comment]
Version key has been added, so that should no longer be an issue. Please try to reinstall the ecovent component via hacs and see if the problem still persists.

**Comment by aleksman-piter** [comment]
Thank you, it helped, I will continue the fun with ecovent
