### ISSUE TITLE
Log warning - device_state_attributes

### ISSUE THREAD

**Issue by mariuske** [aglehmann/home_assistant_ecovent#20]
Running the latest Home Assistant 2021.12.9 version, a log warning for each entity from this integration is displayed. I guess this must be corrected by the integration owner?

> Entity fan.office_flexit_fan (<class 'custom_components.ecovent.fan.EcoventFan'>) implements device_state_attributes. Please report it to the custom component author.
Entity fan.basement_flexit_fan (<class 'custom_components.ecovent.fan.EcoventFan'>) implements device_state_attributes. Please report it to the custom component author.
Entity fan.bedroom_right_flexit_fan (<class 'custom_components.ecovent.fan.EcoventFan'>) implements device_state_attributes. Please report it to the custom component author.
Entity fan.bedroom_left_flexit_fan (<class 'custom_components.ecovent.fan.EcoventFan'>) implements device_state_attributes. Please report it to the custom component author.

**Comment by mariuske** [comment]
Here's a community post with some relevant information:
https://community.home-assistant.io/t/2021-12-new-configuration-menu-the-button-entity-and-gorgeous-area-cards/365680/317

**Comment by mariuske** [comment]
@aglehmann - PR created to resolve these log entries:
https://github.com/aglehmann/home_assistant_ecovent/pull/21#issue-1099110045

**Comment by aglehmann** [comment]
PR merged and closed
