### ISSUE TITLE
Deprecated properties

### ISSUE THREAD

**Issue by tarinjames** [aglehmann/home_assistant_ecovent#23]
https://developers.home-assistant.io/docs/core/entity/fan/#deprecated-properties

Is there a need to implement further support for preset_modes and percentage for fan control (the code still seems to refer to speed_list and speed)?

**Comment by mariuske** [comment]
These properties have now been removed in 2022.2 and this custom integration has stopped working with numerous errors in the log.

**Comment by aglehmann** [comment]
I'll see if I can find time to do some work on this component again sometime in the near future.

**Comment by mariuske** [comment]
@aglehmann - Please see #21 for a proposed solution to this issue.

**Comment by aglehmann** [comment]
PR merged and closed
