### ISSUE TITLE
Fan speed not working

### ISSUE THREAD

**Issue by mycortex** [aglehmann/home_assistant_ecovent#3]
Hi and thank you for this component! Have been looking for a solution for my Flexit Roomie Dual Wifi in HA for a while.

Currently running Home Assistant 0.105.1

Turning on/off works as it should, but the fan speed isn't responding. It seems like no command is received by the fan. No beep sound. I haven't found any command documentation about the Flexit, only Blauberg, so I have no clue what could be wrong.

Wireshark picks up this command when changing fan speed to "Medium" with mobile app:
ASCII: mobile\04\02\r\n
HEX: 6d 6f 62 69 6c 65 04 02 0d 0a
This looks like the same command found in the Blauberg docs.

When changing fan speed in HA Wireshark only picks up this command:
ASCII: mobile\01\00\r\n
HEX: 6d 6f 62 69 6c 65 01 00 0d 0a
This is the command for requesting access data. Not setting fan speed.

Is this working on other fans? Do you have any idea what is wrong?

**Comment by aglehmann** [comment]
Hi,
Sorry about the late reply.
The byte pair "01 00" in this "HEX: 6d 6f 62 69 6c 65 **01 00** 0d 0a" equals the command, as stated in the documentation, "Access of data for the control page". Which means that this command won't do anything else than retrieve all current values set on the fan. I have the exact same issue on my HA setup but i don't know why this happens. I need to look into the custom component to figure that out, they might be a change in HA that causes this to happen. I'll get back to once I have looked further into it.

**Comment by mycortex** [comment]
Hi
I you looked into this? Would be nice to be able to set fan speed with this.

**Comment by aglehmann** [comment]
Hi,
Sorry, haven't had much time to look into this yet. Will let you know as soon as I do.

**Comment by aglehmann** [comment]
Hi again,
I have just pushed an updated fan.py which should rectify the issue.
There are quite a few changes to the internals of HA so I should probably re-write more of the custom component.

Please download the updated component and replace the existing one. Please let me know if this works for you.

**Comment by mycortex** [comment]
Hi. Works great. Thank you!
