### ISSUE TITLE
Consider moving to the Home Assistant Community Store

### ISSUE THREAD

**Issue by siku2** [aglehmann/home_assistant_ecovent#6]
[HACS](https://hacs.xyz/) is a way to easily distribute custom integrations or plugins. It provides a solid user experience for adding and removing custom components and it even supports automatic updates.

You can check out my fork [siku2/hass-ecovent](https://github.com/siku2/hass-ecovent) which supports installation through HACS.
If you're interested I can create a PR.

**Comment by Tscherno** [comment]
Thx that was something I had also in mind :)

**Comment by aglehmann** [comment]
Hi,
Please do create a PR, HACS seems like a good idea.

I havent used HACS or looked into it, is the "hacs.json" file all that is required? (apart from adding the custom repo)

**Comment by siku2** [comment]
@aglehmann The only thing that's absolutely necessary for HACS to detect the integration is for it to be placed in a `custom_components` subdirectory ([source](https://hacs.xyz/docs/publish/integration#repository-structure)). Everything else is mostly just to make the user experience better.

You might be interested in [adding this integration to the default HACS 'repository'](https://hacs.xyz/docs/publish/include). That way users don't have to add this as a custom repository first, it would just show up in the list of all integrations.
